service: koding-serverless

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

function:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: "{proxy+}"